### ISSUE TITLE
Typo in "`GetStakeInfoRespose`"

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/wallet-core#120]
**Describe the bug**
There's a typo ("eligiblity" -> "eligibility") [here](https://github.com/dusk-network/wallet-core/blob/main/src/types.rs#L258) and [here](https://github.com/dusk-network/wallet-core/blob/main/src/types.rs#L260).

The name of the function containing this typo seems to be a typo as well: "GetStakeInfoRespose" -> "GetStakeInfoResponse".

See: https://github.com/dusk-network/dusk-wallet-js/pull/106

**Comment by ZER0** [comment]
`wallet-core` is refactored under `rusk` so this does not apply anymore.
